# Generated by Django 2.2.14 on 2021-05-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleOwner',
            fields=[
                ('fullname', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE')], max_length=100)),
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mobileno', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('aadhar', models.BigIntegerField()),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'vehicleowner_table',
            },
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('owner_name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('default', 'Select Type'), ('Bike', 'BIKE'), ('Car', 'CAR')], default='default', max_length=100)),
                ('vehiclename', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('vehicleno', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
                ('image3', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=250)),
                ('rent', models.DecimalField(decimal_places=2, default=1000, max_digits=65)),
            ],
            options={
                'db_table': 'owner_vehicles',
            },
        ),
    ]
