# Generated by Django 2.2.14 on 2021-05-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleowner',
            name='aadhar',
            field=models.BigIntegerField(max_length=12),
        ),
    ]
