# Generated by Django 2.2.14 on 2021-05-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_owner', '0002_auto_20210514_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='capacity',
            field=models.PositiveIntegerField(),
        ),
    ]
