# Generated by Django 2.2.14 on 2021-05-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_owner', '0003_auto_20210514_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicles',
            name='rent',
            field=models.DecimalField(decimal_places=2, max_digits=65),
        ),
    ]
