# Generated by Django 2.2.14 on 2021-05-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_owner', '0004_auto_20210514_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleowner',
            name='aadhar',
            field=models.BigIntegerField(),
        ),
    ]
