# Generated by Django 2.2.14 on 2021-05-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_owner', '0005_auto_20210515_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicles',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
