# Generated by Django 2.2.14 on 2021-05-18 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_owner', '0007_auto_20210516_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleowner',
            name='aadhar',
            field=models.BigIntegerField(validators=[django.core.validators.MaxLengthValidator(limit_value=12), django.core.validators.MinLengthValidator(limit_value=12)]),
        ),
        migrations.AlterField(
            model_name='vehicleowner',
            name='mobileno',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=10), django.core.validators.MaxLengthValidator(limit_value=10)]),
        ),
        migrations.AlterField(
            model_name='vehicleowner',
            name='password',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=6)]),
        ),
        migrations.AlterField(
            model_name='vehicleowner',
            name='pincode',
            field=models.IntegerField(validators=[django.core.validators.MinLengthValidator(limit_value=6), django.core.validators.MaxLengthValidator(limit_value=6)]),
        ),
        migrations.AlterField(
            model_name='vehicles',
            name='vehicleno',
            field=models.CharField(max_length=200, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(limit_value=10), django.core.validators.MaxLengthValidator(limit_value=10)]),
        ),
    ]
