# Generated by Django 2.2.14 on 2021-05-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_owner', '0008_auto_20210518_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleowner',
            name='aadhar',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='vehicleowner',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
