# Generated by Django 2.2.14 on 2021-05-18 09:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_owner', '0010_auto_20210518_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleowner',
            name='aadhar',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=100000000000, message='Enter a 10-digit number'), django.core.validators.MaxValueValidator(limit_value=999999999999, message='Enter a 10-digit number')]),
        ),
        migrations.AlterField(
            model_name='vehicleowner',
            name='pincode',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=100000, message='Enter a 6-digit pincode'), django.core.validators.MaxValueValidator(limit_value=999999, message='Enter a 6-digit pincode')]),
        ),
    ]
