# Generated by Django 2.2.14 on 2021-05-16 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_customer', '0002_auto_20210515_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('vehiclename', models.CharField(max_length=10)),
                ('capacity', models.PositiveIntegerField()),
                ('vehicleno', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=250)),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_mobile', models.CharField(max_length=100)),
                ('rentperday', models.DecimalField(decimal_places=2, max_digits=65)),
                ('days', models.IntegerField()),
                ('totalrent', models.DecimalField(decimal_places=2, max_digits=65)),
            ],
            options={
                'db_table': 'vehicles_orders',
            },
        ),
    ]
