# Generated by Django 2.2.14 on 2021-05-18 05:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_customer', '0004_auto_20210516_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='owner_mobile',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=10), django.core.validators.MaxLengthValidator(limit_value=10)]),
        ),
        migrations.AlterField(
            model_name='orders',
            name='vehicleno',
            field=models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(limit_value=10), django.core.validators.MaxLengthValidator(limit_value=10)]),
        ),
        migrations.AlterField(
            model_name='vehiclecustomer',
            name='aadhar',
            field=models.BigIntegerField(validators=[django.core.validators.MaxLengthValidator(limit_value=12), django.core.validators.MinLengthValidator(limit_value=12)]),
        ),
        migrations.AlterField(
            model_name='vehiclecustomer',
            name='mobileno',
            field=models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(limit_value=10), django.core.validators.MaxLengthValidator(limit_value=10)]),
        ),
        migrations.AlterField(
            model_name='vehiclecustomer',
            name='password',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(limit_value=6)]),
        ),
        migrations.AlterField(
            model_name='vehiclecustomer',
            name='pincode',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(limit_value=6), django.core.validators.MinLengthValidator(limit_value=6)]),
        ),
    ]
