# Generated by Django 2.2.14 on 2021-05-18 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_customer', '0006_auto_20210518_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecustomer',
            name='aadhar',
            field=models.BigIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=100000000000), django.core.validators.MaxValueValidator(limit_value=999999999999)]),
        ),
        migrations.AlterField(
            model_name='vehiclecustomer',
            name='pincode',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=100000), django.core.validators.MaxValueValidator(limit_value=999999)]),
        ),
    ]
